api/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'

urlpatterns = [
    url(r'^clients/', views.ClientList.as_view()),
    #url(r'^fblogin/', views.RegisterClient.as_view()),
    url(r'^fblogin/', views.LoginRegisterFB.as_view()),
    url(r'^preferences/', views.CusineTypes.as_view()),
    url(r'^suscribepreference/', views.SuscribePreference.as_view()),
    url(r'^unsuscribepreference/', views.UnsuscribePreference.as_view()),
    url(r'^updatephone/', views.UpdatePhone.as_view()),
    url(r'^registerTruckGeneralInformation/', views.RegisterTruckGeneralInformation.as_view()),
    url(r'^updateTruckGeneralInformation/', views.UpdateTruckGeneralInformation.as_view()),
    url(r'^updateTruckContactInformation/', views.UpdateTruckContactInformation.as_view()),
    url(r'^updateTruckLogo/', views.UpdateTruckLogo.as_view()),
    url(r'^updateTruckBanner/', views.UpdateTruckBanner.as_view()),
    url(r'^myTrucks/', views.MyTrucks.as_view()),
    url(r'^menu/', views.MenuByTruck.as_view()),
    url(r'^addmenuitem/', views.AddMenuItem.as_view()),
    url(r'^updatemenuitem/', views.UpdateMenuItem.as_view()),
    url(r'^updatemenuphoto/', views.UpdateMenuPhoto.as_view()),
    url(r'^search/', views.QuerySearch.as_view()),
    url(r'^cusinetypes/', views.Cusines.as_view()),
    url(r'^updatePhone/', views.UpdatePhone.as_view()),
    url(r'^languages/', views.Languages.as_view()),
    url(r'^updatelanguage/', views.UpdateLanguage.as_view()),
    #url(r'^updatemenu/', views.UpdateMenu.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'

urlpatterns = [
    url(r'^food/$', views.food, name='food'),
    url(r'^cusine/$', views.cusine, name='cusine'),
]

client/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

app_name = 'client'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^blockManagement/$', views.blockManagement, name='blockManagement'),
    url(r'^clientComplaintResolution/$', views.clientComplaintResolution, name='clientComplaintResolution'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += urlpatterns('django.views.static',(r'^media/(?P<path>.*)','serve',{'document_root':settings.MEDIA_ROOT}), )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complaint/urls.py
from django.conf.urls import url
from . import views

app_name = 'complaint'

urlpatterns = [
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^trucks/$', views.trucks, name='trucks'),
    url(r'^$', views.index, name='index'),
    url(r'^updatecomplaint/$', views.updatecomplaint, name='updatecomplaint'),
]

findmyfood/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include('client.urls')),
    url(r'^truck/', include('truck.urls')),
    url(r'^complaint/', include('complaint.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

truck/urls.py
from django.conf.urls import url
from . import views

app_name = 'truck'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^truckComplaintResolution/$', views.truckComplaintResolution, name='truckComplaintResolution'),
    url(r'^updateTruck/$', views.updateTruck, name='updateTruck'),
    url(r'^blockManagement/$', views.blockManagement, name='blockManagement'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^updateMenuItem/$', views.updateMenuItem, name='updateMenuItem'),
]

client/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Client, Truckreport, Clientreport, Clienttype, Reportresolution, Gender, Search, Usersession, Foodpreference, Clientreporthistory, AuthUser, Language
from django.db.models import Q
import datetime
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

@login_required
def index(request, **kwargs):
	clients = Client.objects

	language = 0
	clientname = ''
	gender = 0
	clientstatus = ''
	fromdate = ''
	todate = ''

	if request.GET.get('clientname'):
		clientname = request.GET['clientname']
		if clientname is None:
			clientname = ''
		clients = clients.filter(Q(name__icontains=request.GET['clientname']) | Q(lastname__icontains=request.GET['clientname']))

	if request.GET.get('gender'):
		gender = int(request.GET['gender'])
		clients = clients.filter(id_gender=gender)

	if request.GET.get('language'):
		language = int(request.GET['language'])
		clients = clients.filter(id_language=language)

	if request.GET.get('clientstatus'):
		clientstatus = request.GET.get('clientstatus')
		clients = clients.filter(active=bool(int(request.GET.get('clientstatus'))))

	if request.GET.get('fromdate'):
		fromdate = request.GET.get('fromdate')
		clients = clients.filter(created_at__gte=fromdate)

	if request.GET.get('todate'):
		todate = request.GET.get('todate')
		clients = clients.filter(created_at__lte=todate)

	clients = clients.order_by('name')[:100]
	languages = Language.objects.order_by('language').all
	genders = Gender.objects.order_by('gender').all

	context = { 
				'clients': clients, 
				'languages': languages, 
				'genders': genders, 
				'clientname': clientname, 
				'language': language, 
				'gender': gender, 
				'clientstatus': clientstatus, 
				'todate': todate, 
				'fromdate': fromdate 
			}
	return render(request, 'client/index.html', context)

@login_required
def detail(request, id):
	fromdate = ''
	todate = ''

	client = Client.objects.get(id = id)
	truckreports = Truckreport.objects.filter(id_client=id)
	clientreports = Clientreport.objects.filter(id_client_reported=id)
	search = Search.objects.filter(id_usersession__id_client=id)
	sessions = Usersession.objects.filter(id_client=id)
	cusinepreferences = Foodpreference.objects.filter(id_client=id).order_by('created_at')

	if request.GET.get('fromdate'):
		fromdate = request.GET.get('fromdate')
		clientreports = clientreports.filter(created_at__gte=fromdate)
		truckreports = truckreports.filter(created_at__gte=fromdate)
		search = search.filter(created_at__gte=fromdate)
		sessions = sessions.filter(created_at__gte=fromdate)

	if request.GET.get('todate'):
		todate = request.GET.get('todate')
		clientreports = clientreports.filter(created_at__lte=todate)
		truckreports = truckreports.filter(created_at__lte=todate)
		search = search.filter(created_at__lte=todate)
		sessions = sessions.filter(created_at__lte=todate)

	truckreports = truckreports.order_by('created_at')[:100]
	clientreports = clientreports.order_by('created_at')[:100]
	search = search.order_by('created_at')[:100]
	sessions = sessions.order_by('created_at')[:100]

	reportresolutions = Reportresolution.objects.order_by('resolution').all
	context = {'client': client, 'truckreports': truckreports, 'clientreports': clientreports, 'search': search, 'sessions': sessions, 'reportresolutions': reportresolutions, 'cusinepreferences': cusinepreferences, 'fromdate': fromdate, 'todate': todate }
	return render(request, 'client/detail.html', context) 

@login_required
def blockManagement(request):
	id = int(request.POST.get('id'))
	active = int(request.POST.get('active'))
	Client.objects.filter(id = id).update(active = active)
	return JsonResponse({'success': True})

@login_required
def clientComplaintResolution(request):
	id = int(request.POST.get('id'))
	idResolution = int(request.POST.get('resolution'))
	Clientreport.objects.filter(id = id).update(id_resolutiontype = idResolution)

	crh = Clientreporthistory()
	crh.id_clientreport = Clientreport(id=id)
	crh.id_reportresolution = Reportresolution(id=idResolution)
	crh.id_auth_user = AuthUser(id=request.user.id)
	crh.created_at = datetime.datetime.now()
	crh.save()
	return JsonResponse({'success': True})

client/templates/client/base.html
<!DOCTYPE>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>{% block title %}Find my food{% endblock %}</title>

		{% load staticfiles %}
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" /> 
		<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.growl.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{% static 'js/jquery.growl.js' %}" ></script> 
		<script type="text/javascript" src="{% static 'js/management.js' %}" ></script> 
		<script type="text/javascript" src="{% static 'js/fmf.js' %}" ></script> 

		<link rel="icon" type="image/png" href="{% static 'images/favicon-32x32.png' %}" sizes="32x32" />
		<link rel="icon" type="image/png" href="{% static 'images/favicon-16x16.png' %}" sizes="32x32" />
	</head>

	<body>
		{% if user.is_authenticated %}
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toogle="collapse" data-target="#topNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'client:index' %}">
						<img src="{% static 'images/full-logo.png' %}" class="logo" style="width: 100px; "/>
					</a>
				</div>
				<div class="collapse navbar-collapse" id="topNavBar">
					<ul class="nav navbar-nav">
						<li class="">
							<a href="{% url 'client:index' %}">
								<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
								Clients
							</a>
						</li>
						<li class="">
							<a href="{% url 'truck:index' %}">
								<span class="glyphicon glyphicon-road" aria-hidden="true"></span>
								Trucks
							</a>
						</li>


						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">Complaints
							<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li class="">
									<a href="{% url 'complaint:clients' %}">
										<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
										Client complaint
									</a>
								</li>
								<li class="divider"></li>
								<li class="">
									<a href="{% url 'complaint:trucks' %}">
										<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
										Truck complaint
									</a>
								</li>
								<li class="divider"></li>
								<li class="">
									<a href="{% url 'complaint:index' %}">
										<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
										Manage complaint types
									</a>
								</li>
							</ul>
						</li>

						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">Catalogs
							<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li class="">
									<a href="{% url 'catalog:food' %}">
										<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
										Food type
									</a>
								</li>
								<li class="divider"></li>
								<li class="">
									<a href="{% url 'catalog:cusine' %}">
										<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
										Cusine type
									</a>
								</li>
							</ul>
						</li>

						<li class="">
							<a href="#">
								<span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>
								Payments
							</a>
						</li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Welcome: {{ request.user.username }}</a>
						</li>
						<li>
							<a href="/account/logout/">
								<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
									Logout
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		{% endif %}
		<div id="main">
			{% block body %}
			{% endblock %}
		</div>
		<div id="clientprofile">
		</div>
		<div id="turckprofile"></div>

		<footer>
			<div class="footer1">
				<img src="{% static 'images/full-logo.png' %}" class="logo" style="width: 100px; "/>
			</div>
			<div class="footer2"><p>Find my food &copy; - All rights reserved<p></div>
		</footer>
	</body>
	
</html>

client/templates/client/detail.html
{% extends 'client/base.html' %}

{% block body %}

<script>
	$(function(){
		$("#btn-block").on("click", function(){
			if (confirm('Are you sure you want to block this user?')) {
				blockManagement({{ client.id }}, 0, "{% url 'client:blockManagement' %}");
			}
		});

		$("#btn-reactive").on("click", function(){
			if (confirm('Are you sure you want to unblock this user?')) {
				blockManagement({{ client.id }}, 1, "{% url 'client:blockManagement' %}");
			}
		});

		$(".truckResolution").on("click", function(){
			var id = $(this).attr("id").split("-")[1];
			if( $("#tr-" + id +  " option:selected").val() != "")
				truckResolveComplaint(id, $("#tr-" + id +  " option:selected").val(), "{% url 'truck:truckComplaintResolution' %}");
		});

		$(".clientResolution").on("click", function(){
			var id = $(this).attr("id").split("-")[1];
			if( $("#cr-" + id +  " option:selected").val() != "")
				clientResolveComplaint(id, $("#cr-" + id + " option:selected").val(), "{% url 'client:clientComplaintResolution' %}");
		});
	});

</script>

<h2>{{ client.name }} {{ client.lastname }}</h2>

<div class="col-lg-12 col-md-12">
	{% if client.picture != '' and  client.picture  != None %}
	<div class="col-lg-2 col-md-2 form-group">
		<img src="{{ client.picture }}" class="photo" />
	</div>
	{% endif %}
	<div class="col-lg-3 col-md-3">
		<p>Gender: {{ client.id_gender.gender }}</p>
		<p>Email: {{ client.email }}</p>
		<p>Phone: {{ client.phone }}</p>
		<p>Active since: {{ client.created_at }}</p>
	</div>
	<div class="col-lg-3 col-md-3">
		<p>Active: {{ client.active }}</p>
		<p>Application language in use: {{ client.id_language.language }}</p>
		<p>Device language in use: {{ client.registeredlanguage }}</p>
	</div>
</div>

<div class="col-lg-12 col-md-12">
	{% if client.active %}
		<input type="submit" value="Block this user" class="btn btn-primary" id="btn-block" />
	{% else %}
		<input type="submit" value="Reactive this user" class="btn btn-primary" id="btn-reactive" />
	{% endif %}
</div>

<div class="col-lg-12 col-md-12"><hr /> </div>
<ul class="nav nav-tabs">
	<li class="active"><a data-toggle="tab" href="#option1">Complaints by me</a></li>
	<li><a data-toggle="tab" href="#option2">Complaints about {{ client.name }}</a></li>
	<li><a data-toggle="tab" href="#option6">Cusine preferences</a></li>
	<li><a data-toggle="tab" href="#option3">Search history</a></li>
	<li><a data-toggle="tab" href="#option4">Session history</a></li>
	<li><a data-toggle="tab" href="#option5">Orders history</a></li>
</ul>

<div class="tab-content">
	<div class="col-lg-12 col-md-12">
		<form method="GET" action="{% url 'client:detail' client.id %}" >
			<div class="form-group col-lg-1 col-md-1">
				<label>From date:</label>
			</div>
			<div class="form-group col-lg-2 col-md-2">
				<input type="date" class="form-control" name="fromdate" value="{{ fromdate }}" />
			</div>
			<div class="form-group col-lg-1 col-md-1">
				<label>To date:</label>
			</div>
			<div class="form-group col-lg-2 col-md-2">
				<input type="date" class="form-control" name="todate" value="{{ todate }}" />
			</div>
			<div class="form-group col-lg-2 col-md-2">
				<input type="submit" value="Search" class="btn btn-primary" />
			</div>
		</form>
	</div>
	<div id="option1" class="tab-pane fade in active">
    	<h3>Complaints by me</h3>
    	<table class="table">
			<thead>
				<tr>
					<th>Reported to</th>
					<th>Complaint</th>
					<th>Date</th>
					<th>Status</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for tr in truckreports %}
				<tr>
					<td>{{ tr.id_truck.truckname }}</td>
					<td>{{ tr.id_reporttype.reporttype }}</td>
					<td>{{ tr.created_at }}</td>
					<td>
						<div class="col-lg-6 col-md-6">
							<select class="form-control" id="tr-{{ tr.id }}">
								<option selected="selected" disabled="disabled" value="">Select a resolution</option>
								{% for item in reportresolutions %}
								<option value="{{ item.id }}" {% ifequal tr.id_resolutiontype.id item.id %}selected{% endifequal %}>{{ item.resolution }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-lg-4 col-md-4">
							<input type="submit" id="btntr-{{ tr.id }}" value="Accept" class="btn btn-primary truckResolution" />
						</div>
					</td>
				</tr>
				{% endfor %}
				{% if truckreports.count == 0 %}
				<tr>
					<td colspan="100">The client has not any complaint registered</td>
				</tr>
				{% endif %}
			</tbody>
		</table>
  	</div>
  	<div id="option2" class="tab-pane fade">
    	<h3>Complaints about {{ client.name }}</h3>
    	<table class="table">
			<thead>
				<tr>
					<th>Reported by</th>
					<th>Complaint</th>
					<th>Date</th>
					<th>Resolution</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for cr in clientreports %}
				<tr>
					<td>{{ cr.id_truck.truckname }} | {{ cr.id_client_truck.name }} {{ cr.id_client_truck.lastname }}</td>
					<td>{{ cr.id_reporttype.reporttype }}</td>
					<td>{{ cr.created_at }}</td>
					<td>
						<select class="form-control" id="cr-{{ cr.id }}">
							<option selected="selected" disabled="disabled">Select a resolution</option>
							{% for item in reportresolutions %}
							<option value="{{ item.id }}" {% ifequal cr.id_resolutiontype.id item.id %}selected{% endifequal %}>{{ item.resolution }}</option>
							{% endfor %}
						</select>
					</td>
					<td>
						<input type="submit" value="Accept" class="btn btn-primary clientResolution" id="btncr-{{ cr.id }}" />
					</td>
				</tr>
				{% endfor %}
				{% if clientreports.count == 0 %}
				<tr>
					<td colspan="100">The client has not any complaint registered</td>
				</tr>
				{% endif %}
			</tbody>
		</table>
  	</div>
  	<div id="option3" class="tab-pane fade">
  		<h3>Search history</h3>
  		<table class="table">
  			<thead>
  				<tr>
  					<th>Searched terms</th>
  					<th>Searched date</th>
  					<th>Device</th>
  					<th>Location</th>
  				</tr>
  			</thead>
  			<tbody>
  				{% for item in search %}
	  			<tr>
	  				<td>{{ item.searchedtext }}</td>
	  				<td>{{ item.created_at }}</td>
	  				<td>{{ item.id_usersession.id_device.device }}</td>
	  				<td>{{ item.id_usersession.latitude }},{{ item.id_usersession.longitude }}</td>
	  			</tr>
	  			{% endfor %}
	  			{% if search.count == 0%}
	  			<tr>
	  				<td colspan="100">The client has no any search</td>
	  			</tr>
	  			{% endif %}
  			</tbody>
  		</table>
  	</div>
  	<div id="option4" class="tab-pane fade">
  		<h3>Session history</h3>
  		<table class="table">
  			<thead>
  				<tr>
  					<th>Date</th>
  					<th>Device</th>
  					<th>Location</th>
  					<th></th>
  				</tr>
  			</thead>
  			<tbody>
  				{% for item in sessions %}
  				<tr>
  					<td>{{ item.created_at }}</td>
  					<td>{{ item.id_device.device }}</td>
  					<td>{{ item.latitude }},{{ item.longitude }}</td>
  					<td><a href="#">View on map</a></td>
  				</tr>
  				{% endfor %}
  				{% if sessions.count == 0%}
	  			<tr>
	  				<td colspan="100">The client has no any search</td>
	  			</tr>
	  			{% endif %}
  			</tbody>
  		</table>
  	</div>
	<div id="option5" class="tab-pane fade">
    	<h3>Orders</h3>
    	<table class="table">
			<thead>
				<tr>
					<th>Truck name</th>
					<th>Date</th>
					<th>Status</th>
					<th>Ammount</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td colspan="100">This feaute is under development</td>
				</tr>
			</tbody>
		</table>
  	</div>
  	<div id="option6" class="tab-pane fade">
    	<h3>Cusine preferences</h3>
    	<table class="table">
    		<thead>
    			<tr>
    				<th>Preferences</th>
    			</tr>
    		</thead>
    		<tbody>
    			{% for item in cusinepreferences %}
    			<tr>
    				<td>{{ item.id_cusinetype.trucktype_en }}</td>
    			</tr>
    			{% endfor %}
    			{% if cusinepreferences.count == 0 %}
    			<tr>
    				<td>The client has no added any cuisine preference</td>
    			</tr>
    			{% endif %}
    		</tbody>
    	</table>
    		
    	</ul>
  	</div>
</div>

{% endblock %}

client/templates/client/index.html
{% extends 'client/base.html' %}

{% block body %}

<div class="col-lg-12 col-md-12 col-sm-12">
	<form method="get">
		{% csrf_token %}
		<fieldset>
			<legend>Client management</legend>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Name</label>
				<input name="clientname" type="text" class="form-control" value="{{ clientname }}" />
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Gender</label>
				<select name="gender" class="form-control">
					<option value="">All</option>
					{% for item in genders %}
					<option value="{{ item.id }}" {% ifequal gender item.id %}selected{% endifequal %}>{{ item.gender }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Language in use</label>
				<select name="language" class="form-control">
					<option value="">All</option>
					{% for item in languages %}
					<option value="{{ item.id }}" {% ifequal language item.id %}selected{% endifequal %}>{{ item.language }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Client status</label>
				<select name="clientstatus" class="form-control">
					<option value="">All</option>
					<option value="1" {% ifequal clientstatus "1" %}selected{% endifequal %}>Active</option>
					<option value="0" {% ifequal clientstatus "0" %}selected{% endifequal %}>Inactive</option>
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Registered since</label>
				<input name="fromdate" value="{{ fromdate }}" type="date" class="form-control" />
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Registered to</label>
				<input name="todate" type="date" value="{{ todate }}" class="form-control" />
			</div>
			<div class="col-lg-12 col-md-12 form-group">
				<input type="submit" value="Filter clients" class="btn btn-primary" />
			</div>
		</fieldset>
	</form>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Registered date</th>
			<th>Registered language</th>
			<th>Language in use</th>
			<th>Is active?</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for client in clients %}
		<tr>
			<td>{{ client.name }} {{ client.lastname }}</td>
			<td>{{ client.email }}</td>
			<td>{{ client.id_gender.gender }}</td>
			<td>{{ client.created_at }}</td>
			<td>{{ client.registeredlanguage }}</td>
			<td>{{ client.id_language.language }}</td>
			<td>{{ client.active }}</td>
			<td><a href="{% url 'client:detail' client.id %}">Manage</a></td>
		</tr>
		{% endfor %}
		{% if clients.count == 0 %}
		<tr>
			<td colspan="100">No clients were found with the current filters</td>
		</tr>
		{% endif %}
	</tbody>
</table>

{% endblock %}