api/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'

urlpatterns = [
    url(r'^clients/', views.ClientList.as_view()),
    #url(r'^fblogin/', views.RegisterClient.as_view()),
    url(r'^fblogin/', views.LoginRegisterFB.as_view()),
    url(r'^preferences/', views.CusineTypes.as_view()),
    url(r'^suscribepreference/', views.SuscribePreference.as_view()),
    url(r'^unsuscribepreference/', views.UnsuscribePreference.as_view()),
    url(r'^updatephone/', views.UpdatePhone.as_view()),
    url(r'^registerTruckGeneralInformation/', views.RegisterTruckGeneralInformation.as_view()),
    url(r'^updateTruckGeneralInformation/', views.UpdateTruckGeneralInformation.as_view()),
    url(r'^updateTruckContactInformation/', views.UpdateTruckContactInformation.as_view()),
    url(r'^updateTruckLogo/', views.UpdateTruckLogo.as_view()),
    url(r'^updateTruckBanner/', views.UpdateTruckBanner.as_view()),
    url(r'^myTrucks/', views.MyTrucks.as_view()),
    url(r'^menu/', views.MenuByTruck.as_view()),
    url(r'^addmenuitem/', views.AddMenuItem.as_view()),
    url(r'^updatemenuitem/', views.UpdateMenuItem.as_view()),
    url(r'^updatemenuphoto/', views.UpdateMenuPhoto.as_view()),
    url(r'^search/', views.QuerySearch.as_view()),
    url(r'^cusinetypes/', views.Cusines.as_view()),
    url(r'^updatePhone/', views.UpdatePhone.as_view()),
    url(r'^languages/', views.Languages.as_view()),
    url(r'^updatelanguage/', views.UpdateLanguage.as_view()),
    #url(r'^updatemenu/', views.UpdateMenu.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

client/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

app_name = 'client'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^blockManagement/$', views.blockManagement, name='blockManagement'),
    url(r'^clientComplaintResolution/$', views.clientComplaintResolution, name='clientComplaintResolution'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += urlpatterns('django.views.static',(r'^media/(?P<path>.*)','serve',{'document_root':settings.MEDIA_ROOT}), )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complaint/urls.py
from django.conf.urls import url
from . import views

app_name = 'complaint'

urlpatterns = [
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^trucks/$', views.trucks, name='trucks'),
    url(r'^$', views.index, name='index'),
    url(r'^updatecomplaint/$', views.updatecomplaint, name='updatecomplaint'),
]

truck/urls.py
from django.conf.urls import url
from . import views

app_name = 'truck'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^truckComplaintResolution/$', views.truckComplaintResolution, name='truckComplaintResolution'),
    url(r'^updateTruck/$', views.updateTruck, name='updateTruck'),
    url(r'^blockManagement/$', views.blockManagement, name='blockManagement'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^updateMenuItem/$', views.updateMenuItem, name='updateMenuItem'),
]

complaint/models.py
from django.db import models

# Create your models here.

truck/models.py
from django.db import models

# Create your models here.

client/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Client, Truckreport, Clientreport, Clienttype, Reportresolution, Gender, Search, Usersession, Foodpreference, Clientreporthistory, AuthUser, Language
from django.db.models import Q
import datetime
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

@login_required
def index(request, **kwargs):
	clients = Client.objects

	language = 0
	clientname = ''
	gender = 0
	clientstatus = ''
	fromdate = ''
	todate = ''

	if request.GET.get('clientname'):
		clientname = request.GET['clientname']
		if clientname is None:
			clientname = ''
		clients = clients.filter(Q(name__icontains=request.GET['clientname']) | Q(lastname__icontains=request.GET['clientname']))

	if request.GET.get('gender'):
		gender = int(request.GET['gender'])
		clients = clients.filter(id_gender=gender)

	if request.GET.get('language'):
		language = int(request.GET['language'])
		clients = clients.filter(id_language=language)

	if request.GET.get('clientstatus'):
		clientstatus = request.GET.get('clientstatus')
		clients = clients.filter(active=bool(int(request.GET.get('clientstatus'))))

	if request.GET.get('fromdate'):
		fromdate = request.GET.get('fromdate')
		clients = clients.filter(created_at__gte=fromdate)

	if request.GET.get('todate'):
		todate = request.GET.get('todate')
		clients = clients.filter(created_at__lte=todate)

	clients = clients.order_by('name')[:100]
	languages = Language.objects.order_by('language').all
	genders = Gender.objects.order_by('gender').all

	context = { 
				'clients': clients, 
				'languages': languages, 
				'genders': genders, 
				'clientname': clientname, 
				'language': language, 
				'gender': gender, 
				'clientstatus': clientstatus, 
				'todate': todate, 
				'fromdate': fromdate 
			}
	return render(request, 'client/index.html', context)

@login_required
def detail(request, id):
	fromdate = ''
	todate = ''

	client = Client.objects.get(id = id)
	truckreports = Truckreport.objects.filter(id_client=id)
	clientreports = Clientreport.objects.filter(id_client_reported=id)
	search = Search.objects.filter(id_usersession__id_client=id)
	sessions = Usersession.objects.filter(id_client=id)
	cusinepreferences = Foodpreference.objects.filter(id_client=id).order_by('created_at')

	if request.GET.get('fromdate'):
		fromdate = request.GET.get('fromdate')
		clientreports = clientreports.filter(created_at__gte=fromdate)
		truckreports = truckreports.filter(created_at__gte=fromdate)
		search = search.filter(created_at__gte=fromdate)
		sessions = sessions.filter(created_at__gte=fromdate)

	if request.GET.get('todate'):
		todate = request.GET.get('todate')
		clientreports = clientreports.filter(created_at__lte=todate)
		truckreports = truckreports.filter(created_at__lte=todate)
		search = search.filter(created_at__lte=todate)
		sessions = sessions.filter(created_at__lte=todate)

	truckreports = truckreports.order_by('created_at')[:100]
	clientreports = clientreports.order_by('created_at')[:100]
	search = search.order_by('created_at')[:100]
	sessions = sessions.order_by('created_at')[:100]

	reportresolutions = Reportresolution.objects.order_by('resolution').all
	context = {'client': client, 'truckreports': truckreports, 'clientreports': clientreports, 'search': search, 'sessions': sessions, 'reportresolutions': reportresolutions, 'cusinepreferences': cusinepreferences, 'fromdate': fromdate, 'todate': todate }
	return render(request, 'client/detail.html', context) 

@login_required
def blockManagement(request):
	id = int(request.POST.get('id'))
	active = int(request.POST.get('active'))
	Client.objects.filter(id = id).update(active = active)
	return JsonResponse({'success': True})

@login_required
def clientComplaintResolution(request):
	id = int(request.POST.get('id'))
	idResolution = int(request.POST.get('resolution'))
	Clientreport.objects.filter(id = id).update(id_resolutiontype = idResolution)

	crh = Clientreporthistory()
	crh.id_clientreport = Clientreport(id=id)
	crh.id_reportresolution = Reportresolution(id=idResolution)
	crh.id_auth_user = AuthUser(id=request.user.id)
	crh.created_at = datetime.datetime.now()
	crh.save()
	return JsonResponse({'success': True})

complaint/views.py
from django.shortcuts import render
from django.http import HttpResponse
from client.models import Clientreport, Truckreport, Reporttype, Reportresolution, Client
from django.db.models import Q
from django.db.models import Max, F
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

@login_required
def clients(request):
	clientreports = Clientreport.objects
	complainttype = 0
	complaintstatus = 1
	clientname = ''
	truckname = ''
	fromdate = ''
	todate = ''

	if request.GET.get('complainttype'):
		complainttype = int(request.GET['complainttype'])
		clientreports = clientreports.filter(id_reporttype=complainttype)

	if request.GET.get('complaintstatus'):
		complaintstatus = int(request.GET['complaintstatus'])
		if complaintstatus == 1:
			clientreports = clientreports.filter(id_resolutiontype__isnull=True)
	else:
		clientreports = clientreports.filter(id_resolutiontype__isnull=True)

	if request.GET.get('clientname'):
		clientname = request.GET.get('clientname')
		if clientname is None:
			clientname = ''
		clientreports = clientreports.filter(Q(id_client_reported__name__icontains=clientname) | Q(id_client_reported__lastname__icontains=clientname) | Q(id_client_truck__name__icontains=clientname) | Q(id_client_truck__lastname__icontains=clientname))

	if request.GET.get('truckname'):
		truckname = request.GET.get('truckname')
		if truckname is None:
			truckname = ''
		clientreports = clientreports.filter(Q(id_truck__truckname__icontains=truckname) | Q(id_truck__truckname__icontains=truckname))

	if request.GET.get('fromdate'):
		fromdate = request.GET.get('fromdate')
		clientreports = clientreports.filter(created_at__gte=fromdate)

	if request.GET.get('todate'):
		todate = request.GET.get('todate')
		clientreports = clientreports.filter(created_at__lte=todate)

	clientreports = clientreports.order_by('created_at')[:100]

	reporttypes = Reporttype.objects.filter(forclient = True).order_by('reporttype').all()
	reportresolutions = Reportresolution.objects.order_by('resolution')
	context = { 'clientreports': clientreports, 'reporttypes': reporttypes, 'reportresolutions': reportresolutions , 'clientname': clientname, 'complainttype': complainttype, 'complaintstatus': complaintstatus, 'truckname': truckname, 'fromdate': fromdate, 'todate': todate }
	return render(request, 'complaint/clients.html', context)

@login_required
def trucks(request):
	truckreports = Truckreport.objects

	complainttype = 0
	complaintstatus = 1
	clientname = ''
	truckname = ''
	fromdate = ''
	todate = ''

	if request.GET.get('complainttype'):
		complainttype = int(request.GET['complainttype'])
		truckreports = truckreports.filter(id_reporttype=complainttype)

	if request.GET.get('complaintstatus'):
		complaintstatus = int(request.GET['complaintstatus'])
		if complaintstatus == 1:
			truckreports = truckreports.filter(id_resolutiontype__isnull=True)
	else:
		truckreports = truckreports.filter(id_resolutiontype__isnull=True)

	if request.GET.get('clientname'):
		clientname = request.GET.get('clientname')
		if clientname is None:
			clientname = ''
		truckreports = truckreports.filter(Q(id_client__name__icontains=clientname) | Q(id_client_lastname__icontains=clientname))

	if request.GET.get('truckname'):
		truckname = request.GET.get('truckname')
		if truckname is None:
			truckname = ''
		truckreports = truckreports.filter(Q(id_truck__truckname__icontains=truckname) | Q(id_truck__truckname__icontains=truckname))

	if request.GET.get('fromdate'):
		fromdate = request.GET.get('fromdate')
		truckreports = truckreports.filter(created_at__gte=fromdate)

	if request.GET.get('todate'):
		todate = request.GET.get('todate')
		truckreports = truckreports.filter(created_at__lte=todate)

	reporttypes = Reporttype.objects.filter(fortruck = True).order_by('reporttype').all()
	reportresolutions = Reportresolution.objects.order_by('resolution')
	truckreports = truckreports.order_by('created_at')[:100]

	context = { 'truckreports' : truckreports, 'reporttypes': reporttypes, 'reportresolutions': reportresolutions , 'clientname': clientname, 'complainttype': complainttype, 'complaintstatus': complaintstatus, 'truckname': truckname, 'fromdate': fromdate, 'todate': todate }
	return render(request, 'complaint/trucks.html', context)

@login_required
def index(request):
	reporttypes = Reporttype.objects
	reporttypes = reporttypes.order_by('reporttype')
	context = { 'reporttypes': reporttypes }
	return render(request, 'complaint/index.html', context)

@login_required
def updatecomplaint(request):
	id = int(request.POST.get('id'))
	forclient = bool(int(request.POST.get('forclient')))
	fortruck = bool(int(request.POST.get('fortruck')))
	active = bool(int(request.POST.get('active')))
	update = {
				'forclient': forclient, 
				'fortruck': fortruck, 
				'active': active
			}
	Reporttype.objects.filter(id = id).update(**update)
	return JsonResponse({'success': True})

client/templates/complaint/clients.html
{% extends 'client/base.html' %}

{% block body %}

<script>
	$(function(){
		$(".clientResolution").on("click", function(){
			var id = $(this).attr("id").split("-")[1];
			if( $("#cr-" + id +  " option:selected").val() != "")
				clientResolveComplaint(id, $("#cr-" + id + " option:selected").val(), "{% url 'client:clientComplaintResolution' %}");
		});
	});
</script>

<div class="col-lg-12 col-md-12 col-sm-12">
	<form method="GET">
		<fieldset>
			<legend>Registered client complaints</legend>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Client name</label>
				<input type="text" class="form-control" name="clientname" value="{{ clientname }}" />
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Truck</label>
				<input type="text" class="form-control" name="truckname" value="{{ truckname }}"/>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Complaint type</label>
				<select class="form-control" name="complainttype">
					<option value="">All</option>
					{% for item in reporttypes %}
					<option value="{{ item.id }}" {% ifequal complainttype item.id %}selected{% endifequal %}>{{ item.reporttype }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Status</label>
				<select name="complaintstatus" class="form-control">
					<option value="1" {% ifequal complaintstatus 1 %}selected{% endifequal %}>Active</option>
					<option value="0" {% ifequal complaintstatus 0 %}selected{% endifequal %}>Resolved</option>
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Reported since</label>
				<input type="date" class="form-control" name="fromdate" value="{{ fromdate }}" />
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Reported to</label>
				<input type="date" class="form-control" name="todate" value="{{ todate }}" />
			</div>
			<div class="col-lg-12 col-md-12 form-group">
				<input type="submit" value="Filter complaints" class="btn btn-primary" />
			</div>
		</fieldset>
	</form>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Reported by</th>
			<th>Reported to</th>
			<th>Complaint</th>
			<th>Date</th>
			<th>Resolution</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for cr in clientreports %}
		<tr>
			<td>{{ cr.id_truck.truckname }} | {{ cr.id_client_truck.name }} {{ cr.id_client_truck.lastname }} </td>
			<td>{{ cr.id_client_reported.name }} {{ cr.id_client_reported.lastname }}</td>
			<td>{{ cr.id_reporttype.reporttype }}</td>
			<td>{{ cr.created_at }}</td>
			<td>
				<div class="col-lg-6 col-md-6">
					<select class="form-control" id="cr-{{ cr.id }}">
						<option selected="selected" disabled="disabled">Select a resolution</option>
						{% for item in reportresolutions %}
						<option value="{{ item.id }}" {% ifequal cr.id_resolutiontype.id item.id %}selected{% endifequal %}>{{ item.resolution }}</option>
						{% endfor %}
					</select>
				</div>
				<div class="col-lg-4 col-md-4">
					<input type="submit" value="Accept" class="btn btn-primary clientResolution" id="btncr-{{ cr.id }}" />
				</div>
			</td>
		</tr>
		{% endfor %}
		{% if clientreports.count == 0 %}
		<tr>
			<td colspan="100">No client compalaints were found with the current filters</td>
		</tr>
		{% endif %}
	</tbody>
</table>

{% endblock %}

client/templates/complaint/index.html
{% extends 'client/base.html' %}

{% block body %}

<script>
	$(function(){
		$(".upudate-rt").on("click", function() {
			var id = $(this).attr("id").split("-")[1];
			var data = $("#rt-" + id + " :input[type='checkbox']");
			var forclient = ($("#rt-" + id + " [name=forclient]").prop("checked") == true) ? 1 : 0;
			var fortruck = ($("#rt-" + id + " [name=fortruck]").prop("checked") == true) ? 1 : 0;
			var active = ($("#rt-" + id + " [name=active]").prop("checked") == true) ? 1 : 0;
			
			$.ajax({
 				type: 'POST',
 				dataType: 'json',
 				url: "{% url 'complaint:updatecomplaint' %}",
 				data: {id: id, forclient: forclient, fortruck: fortruck, active: active },
 				success: function(data) {
 					$.growl({ title: "Find my food", message: "The complaint was updated." });
 				}
			});
		});
	});
</script>

<fieldset>
	<legend>Complaints</legend>
</fieldset>

<table class="table">
	<thead>
		<tr>
			<th>Complaint name</th>
			<th>Available for clients</th>
			<th>Available for trucks</th>
			<th>Active</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for rt in reporttypes %}
		<tr id="rt-{{ rt.id }}">
			<td>{{ rt.reporttype }}</td>
			<td>
				{% if rt.forclient == False %}
				<input type="checkbox" name="forclient" />
				{% else %}
				<input type="checkbox" checked="checked" name="forclient" />
				{% endif %}
			</td>
			<td>
				{% if rt.fortruck == False %}
				<input type="checkbox" name="fortruck" />
				{% else %}
				<input type="checkbox" checked="checked" name="fortruck" />
				{% endif %}
			</td>
			<td>{% if rt.active == False %}
				<input type="checkbox" name="active" />
				{% else %}
				<input type="checkbox" checked="checked" name="active" />
				{% endif %}</td>
			<td> <input type="button" value="Update" class="btn btn-primary upudate-rt" id="urt-{{ rt.id }}" /> </td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

client/templates/complaint/trucks.html
{% extends 'client/base.html' %}

{% block body %}

<script>
	$(function(){
		$(".truckResolution").on("click", function(){
			var id = $(this).attr("id").split("-")[1];
			if( $("#tr-" + id +  " option:selected").val() != "")
				truckResolveComplaint(id, $("#tr-" + id +  " option:selected").val(), "{% url 'truck:truckComplaintResolution' %}");
		});
	})
</script>

<div class="col-lg-12 col-md-12 col-sm-12">
	<form method="GET">
		<fieldset>
			<legend>Registered client complaints</legend>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Client name</label>
				<input type="text" class="form-control" name="clientname" value="{{ clientname }}" />
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Truck</label>
				<input type="text" class="form-control" name="truckname" value="{{ truckname }}"/>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Complaint type</label>
				<select class="form-control" name="complainttype">
					<option value="">All</option>
					{% for item in reporttypes %}
					<option value="{{ item.id }}" {% ifequal complainttype item.id %}selected{% endifequal %}>{{ item.reporttype }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Status</label>
				<select name="complaintstatus" class="form-control">
					<option value="1" {% ifequal complaintstatus 1 %}selected{% endifequal %}>Active</option>
					<option value="0" {% ifequal complaintstatus 0 %}selected{% endifequal %}>Resolved</option>
				</select>
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Reported since</label>
				<input type="date" class="form-control" name="fromdate" value="{{ fromdate }}" />
			</div>
			<div class="col-lg-2 col-md-2 form-group">
				<label>Reported to</label>
				<input type="date" class="form-control" name="todate" value="{{ todate }}" />
			</div>
			<div class="col-lg-12 col-md-12 form-group">
				<input type="submit" value="Filter complaints" class="btn btn-primary" />
			</div>
		</fieldset>
	</form>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Reported by</th>
			<th>Reported to</th>
			<th>Complaint</th>
			<th>Date</th>
			<th>Resolution</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for tr in truckreports %}
		<tr>
			<td>{{ tr.id_client.name }} {{ tr.id_client.lastname }}</td>
			<td>{{ tr.id_truck.truckname }}</td>
			<td>{{ tr.id_reporttype.reporttype }}</td>
			<td>{{ tr.created_at }}</td>
			<td>
				<div class="col-lg-6 col-md-6">
					<select class="form-control" id="tr-{{ tr.id }}">
						<option selected="selected" disabled="disabled" value="">Select a resolution</option>
						{% for item in reportresolutions %}
						<option value="{{ item.id }}" {% ifequal tr.id_resolutiontype.id item.id %}selected{% endifequal %}>{{ item.resolution }}</option>
								{% endfor %}
					</select>
				</div>
				<div class="col-lg-4 col-md-4">
					<input type="submit" id="btntr-{{ tr.id }}" value="Accept" class="btn btn-primary truckResolution" />
				</div>
			</td>
		</tr>
	{% endfor %}
	{% if truckreports.count == 0 %}
		<tr>
			<td colspan="100">No complaints found</td>
		</tr>
	{% endif %}
	</tbody>
</table>

{% endblock %}